 @startuml
'https://plantuml.com/class-diagram

class ToDoListManager {
    main()
    start()
}
class ToDoListManagerController {
    model : ToDoListModel
}
class ToDoListModel {
    ToDoItem : Collection

    addItem()
    removeItem()
    editItem()
    display()
    load()
    save()
}
class ToDoItem {
    complete : boolean
    name : String
    dueDate : String

    mark(boolean)
    rename(String)
    reschedule(String)

    toString(String)
}
ToDoListModel *-> ToDoItem
ToDoListManagerController *--> ToDoListModel
ToDoListManager -- ToDoListManagerController
@enduml